import csv

header = ["record_id","state","state_abbr","state_fips","jurisdiction_name","jurisdiction_type","geographic_scope","issuing_authority","source_title","citation","source_type","effective_date","revision_date","status","binding_level","uas_topic","regulated_party","regulated_activity","requirement_type","permit_or_approval_required","public_agency_only","commercial_operator_relevance","aec_relevance","summary","practical_interpretation_aec_expert","practical_interpretation_agency_practitioner","practical_interpretation_legal_counsel","source_url","date_accessed","confidence_level","verification_status","notes"]

PENDING = "PENDING — Phase 2"

rows = []

rows.append(["HI-001","Hawaii","HI","15","Hawaii","State","Statewide","Hawaii Legislature","Trespass with an Unmanned Aircraft System","Haw. Rev. Stat. § 711-1114 (Act 58, 2023)","Binding law or regulation","2023","2023","Current / in force","Binding","Trespass / harassment UAS restriction","Any person","Causing a UAS to cross a property line and come within 50 ft of a dwelling to coerce/intimidate/harass, or after notice to desist for any other reason; or taking off/landing in violation of FAA special security instructions or security-sensitive airspace restrictions","Prohibition (misdemeanor), with consent and FAA-authorization exceptions","N/A","No","High","High",
"Haw. Rev. Stat. § 711-1114, added by Act 58 (2023), makes it a misdemeanor to intentionally cause a UAS to cross the property line of another and come within 50 ft of a dwelling to coerce, intimidate, or harass another person, or — after having been given actual notice to desist — for any other reason at all; or to take off or land a UAS in violation of current FAA special security instructions or UAS security-sensitive airspace restrictions. The section does not apply where consent to entry was given by a person with legal authority to consent (or a person lawfully present on the property), or where the operator was authorized by federal regulations and operated the UAS lawfully and consistent with those regulations.",
PENDING, PENDING, PENDING,
"https://law.justia.com/codes/hawaii/title-37/chapter-711/section-711-1114/","2026-08-01","High","Full current statutory text and commentary verified directly against Justia's codification of the 2025 Hawaii Revised Statutes.","The 'after having been given actual notice to desist, for any other reason' clause is broad — an AEC operator who has been asked to stop flying near a specific dwelling should treat continued flights within 50 ft of it as a likely violation even absent harassment intent, unless a federal-authorization or consent exception clearly applies."])

rows.append(["HI-002","Hawaii","HI","15","Hawaii","State","Statewide","Hawaii Legislature","Misuse of Uncrewed Aircraft (First, Second, and Third Degree)","Haw. Rev. Stat. §§ 711-1121, 711-1122, 711-1123 (Act 161, 2024)","Binding law or regulation","2024-07-02","2024-07-02","Current / in force","Binding","Graduated UAS misuse felony framework","Any person","First degree: arming a UAS with a firearm/explosive/electric gun/weapon of mass destruction, interfering with a manned aircraft, delivering prison contraband, or causing serious bodily injury. Second degree: disabling Remote ID transmission, defeating/failing to operate required anti-collision lighting, causing substantial bodily injury, or causing more than $20,000 property damage. Third degree: tampering with a registration number, obstructing a police officer/firefighter, causing bodily injury, causing more than $750 damage, or operating while impaired","Prohibition (three graduated felony tiers)","N/A","No","High","High",
"Act 161 (2024), effective July 2, 2024, created a graduated three-tier felony framework for UAS misuse. Misuse of uncrewed aircraft in the first degree (§ 711-1121) is a Class A felony covering arming a drone with a firearm, explosive, electric gun, or weapon of mass destruction; interfering with or disrupting a manned aircraft; delivering contraband, drugs, or dangerous instruments into a prison; or causing serious bodily injury. Misuse in the second degree (§ 711-1122) is a Class B felony covering disabling a drone's Remote ID transmission, defeating or failing to operate required anti-collision lighting, causing substantial bodily injury, or causing more than $20,000 in property damage. Misuse in the third degree (§ 711-1123) is a Class C felony covering tampering with a registration number, obstructing a police officer or firefighter, causing bodily injury, causing more than $750 in damage, or operating under the influence. An earlier (~2015) provision separately made it unlawful to install or carry weapons aboard a UAS used for commercial purposes flown across or above the State; its exact current codified citation was not independently confirmed and it may now substantially overlap with § 711-1121's weaponization felony.",
PENDING, PENDING, PENDING,
"https://www.capitol.hawaii.gov/hrscurrent/vol14_ch0701-0853/HRS0711/HRS_0711-.htm","2026-08-01","Moderate","Existence, tier structure, effective date, and covered conduct corroborated by multiple secondary legal-summary sources describing Act 161; the full current statutory text of §§ 711-1121 through 711-1123 was not independently fetched and read verbatim in this pass (a direct fetch of the individual Justia section pages returned no retrievable content).","The Remote ID and anti-collision lighting provisions in § 711-1122 (second-degree, Class B felony) are directly relevant to routine AEC commercial operations — equipment malfunction or misconfiguration causing a Remote ID or anti-collision lighting failure could carry felony exposure in Hawaii in a way most other states treat as a lesser (or no) offense. Recommend direct verification of the full statutory text before advising a client on the precise elements and any available defenses."])

rows.append(["HI-003","Hawaii","HI","15","Hawaii","State","Statewide","Hawaii Legislature","Violation of Privacy (Second and First Degree)","Haw. Rev. Stat. §§ 711-1111, 711-1110.9","Binding law or regulation","Current","Unknown","Current / in force","Binding","Privacy / surveillance UAS restriction","Any person","Installing or using a device, including a drone, to observe, record, or broadcast a person in a private place without consent; recording showing the person nude or engaged in sexual activity","Prohibition (misdemeanor, elevated to felony for aggravated conduct)","N/A","No","Moderate","Moderate",
"Haw. Rev. Stat. § 711-1111 (violation of privacy in the second degree) makes it unlawful to install or use a device — including a drone — to observe, record, or broadcast a person in a 'private place' (somewhere a person may reasonably expect to be safe from casual or hostile intrusion) without consent; a basic violation is a misdemeanor (up to 1 year imprisonment, up to a $2,000 fine). Where the recording shows the person nude or engaged in sexual activity, § 711-1110.9 (violation of privacy in the first degree) applies instead, a Class C felony punishable by up to 5 years imprisonment and a $10,000 fine.",
PENDING, PENDING, PENDING,
"https://www.capitol.hawaii.gov/hrscurrent/vol14_ch0701-0853/HRS0711/HRS_0711-1111.htm","2026-08-01","High","Substance corroborated by both a secondary legal-summary source and the official Hawaii Legislature HRS webpage citation; the full current statutory text was not independently fetched and read verbatim in this pass.","Applies only to observation/recording in a place with a reasonable expectation of privacy; routine, visible AEC survey/inspection flights are not the conduct this statute targets, but avoid any flight path or camera framing that could be read as targeting a specific private space."])

rows.append(["HI-004","Hawaii","HI","15","Hawaii (statewide, all Hawaii State Park System land)","State","Statewide (Hawaii State Park System)","Hawaii Department of Land and Natural Resources (DLNR), Division of State Parks","Aircraft Landing/Launching Restriction, Hawaii State Park System","Haw. Admin. R. § 13-146-9 (not § 13-146-35, as several secondary sources incorrectly cite)","Binding administrative regulation, though the rule's own text does not use the terms 'UAS,' 'unmanned aircraft,' or 'drone'","Current (rule compiled June 1999; effective date of current text confirmed only through this compilation)","1999-06 (compilation)","Current / in force, subject to confirming no more recent amendment","Binding, with ambiguous but likely UAS application via cross-reference","State park aircraft restriction","Any person","Landing or launching 'aircraft,' as defined by cross-reference to Haw. Rev. Stat. § 261-1, within the Hawaii State Park System","Prohibition except with written permission of the board or its authorized representative","Yes — written permission from the DLNR Board of Land and Natural Resources or its authorized representative","No","High","High",
"Haw. Admin. R. § 13-146-9 provides: 'No person shall land or launch aircraft, as defined in section 261-1, HRS, including airplanes, airships, balloons, gliders, hang gliders, helicopters, parachutes, dirigibles, and other similar means of conveyance except with the written permission of the board or its authorized representative or in the case of an emergency.' The rule's own text does not separately name UAS/drones, relying instead on the cross-referenced statutory definition of 'aircraft' in Haw. Rev. Stat. § 261-1; DLNR's Division of State Parks is separately reported (via secondary sources) to treat drones as covered by this rule and to require a special-use permit for any drone launch/landing/operation in the state park system, consistent with numerous named state park units (Na Pali Coast, Diamond Head, Waimea Canyon, Iao Valley, among others).",
PENDING, PENDING, PENDING,
"https://dlnr.hawaii.gov/ecosystems/files/2013/09/HRS13-146_State-Parks.pdf","2026-08-01","High","Full rule text verified directly against DLNR's own published compilation of Chapter 13-146; note that this compilation dates to a 1999/2002 amendment cycle and a more recent amendment was not independently ruled out. The correct section number (§ 13-146-9, titled 'Aircraft') was confirmed by direct primary-source review — several secondary drone-law sources incorrectly cite this rule as § 13-146-35, which is actually the unrelated 'Sanitation and Litter' section.","This is a clear example of a secondary-source citation error corrected by direct primary-source verification, consistent with this program's evidentiary standards (Section 4). Confirm the current, most-recently-amended version of § 13-146-9 directly against the Hawaii Administrative Rules database before citing to a client, and confirm DLNR's current special-use-permit process and lead time directly with the Division of State Parks."])

rows.append(["HI-005","Hawaii","HI","15","Hawaii (no enacted statewide UAS preemption statute located)","State (research result — no enacted statute)","Statewide, with a county-by-county ordinance patchwork","Hawaii Legislature (research result — no enacted statute)","No State Preemption of Local UAS Ordinances; County Ordinance Patchwork","N/A — research finding regarding the absence of a comprehensive state preemption statute","Discovery lead — not final authority and not included in the final source register","N/A","N/A","Reviewed — no comprehensive UAS-specific preemption statute located","N/A","State/local regulatory boundary for UAS","County governments (Honolulu, Maui, Hawaii, Kauai)","N/A","N/A","N/A","No","N/A","High (context for local-ordinance risk, even though local ordinances themselves are out of scope this phase)",
"Hawaii has not enacted a comprehensive statewide UAS-preemption statute. Secondary sources describe each of Hawaii's four counties (City and County of Honolulu, and Maui, Hawaii, and Kauai counties) as free to regulate UAS takeoff/landing on county-owned property (though not airspace, which remains federally regulated), and report that county drone ordinances commonly target beach and park access — precisely the areas of greatest interest for tourism and, potentially, AEC coastal/site work.",
PENDING, PENDING, PENDING,
"https://dronelaunchacademy.com/drone-laws-by-state/hawaii/","2026-08-01","Low","This entry reports a research result (absence of a located statewide preemption statute) based on secondary drone-law compilation sources; no comprehensive negative-search confirmation was performed against the full Hawaii Revised Statutes.","Confirm county ordinances (Honolulu, Maui, Hawaii, and Kauai counties each separately) for any specific Hawaii project site in a later research phase before finalizing site-specific flight plans — this is one of relatively few states researched so far without any statewide UAS preemption at all."])

rows.append(["HI-006","Hawaii","HI","15","Hawaii","State","Statewide","Hawaii Board of Registration for Professional Engineers, Architects, Surveyors and Landscape Architects","General Professional-Practice Competency Requirement (no UAS-specific board guidance located)","Haw. Rev. Stat. Ch. 464 — general competency-in-practice framework","Binding administrative regulation","Current","Unknown","Current / in force","Binding (general only — no UAS-specific rule or guidance identified)","General professional licensing competency requirement","Licensed PE/land surveyor","Practicing only in fields in which the licensee is competent by education/experience","N/A","No","No","Low","Moderate",
"Hawaii's licensing framework for professional engineers and land surveyors (Haw. Rev. Stat. Chapter 464, administered by the Board of Registration for Professional Engineers, Architects, Surveyors and Landscape Architects) generally requires licensees to practice only in fields in which they are competent by education and/or experience. No standalone UAS-specific board guidance document was located during this research pass.",
PENDING, PENDING, PENDING,
"https://cca.hawaii.gov/pvl/boards/engineer/","2026-08-01","Low","General statutory framework citation based on general knowledge of Hawaii's licensing structure; not independently re-verified against current board rules in this pass, and no UAS-specific guidance search was confirmed as exhaustive.","Recommend direct verification of current board rules before citing specific rule language to a client."])

rows.append(["HI-007","Hawaii","HI","15","Hawaii (no comprehensive UAS-specific executive order, AG opinion, court decision, or procurement restriction located)","State (research result — categories reviewed)","Statewide","Governor of Hawaii / Hawaii Department of the Attorney General / Hawaii courts / DLNR Division of Conservation and Resources Enforcement (research result — categories reviewed)","Executive Orders, Attorney General Opinions, Court Decisions, Procurement, and DOCARE UAS Enforcement Program","Haw. Rev. Stat. § 199-9 (DOCARE Unmanned Aircraft Systems Program) — noted but not independently read in full; other categories reviewed with no result","Discovery lead — not final authority and not included in the final source register","N/A","N/A","Reviewed — mixed: one applicable agency-program statute identified but not fully verified; other categories show no applicable UAS-specific source located","N/A","General; conservation-enforcement UAS program","N/A","N/A","N/A","No","N/A","N/A","Low",
"No Hawaii gubernatorial executive order specifically and solely addressing UAS regulation was located. No Hawaii Attorney General opinion directly addressing UAS regulation was located. No Hawaii appellate court decision directly construing §§ 711-1114, 711-1121–711-1123, or another UAS-specific statute was located. No Hawaii-specific state-agency UAS procurement restriction was located. Separately, Haw. Rev. Stat. § 199-9 appears to establish an 'unmanned aircraft systems program' for the Department of Land and Natural Resources' Division of Conservation and Resources Enforcement (DOCARE), suggesting DOCARE operates its own UAS program for conservation/enforcement purposes; a direct fetch of this section's full text did not return retrievable content in this pass and it should be revisited to confirm whether it imposes any requirement relevant to private AEC operators (as distinct from authorizing DOCARE's own enforcement UAS use).",
PENDING, PENDING, PENDING,
"https://law.justia.com/codes/hawaii/title-12/chapter-199/section-199-9/","2026-08-01","Low","This entry reports a research result (absence of located sources in most categories, plus one flagged-but-unverified agency-program statute) rather than an affirmative binding authority; no comprehensive negative-search confirmation was performed.","Revisit Haw. Rev. Stat. § 199-9 directly (a fetch attempt in this pass returned no content) to confirm whether the DOCARE UAS program imposes any coordination or notification requirement relevant to private AEC operators working near DLNR-managed conservation land."])

with open("HI_UAS_Source_Register.csv", "w", newline="", encoding="utf-8") as f:
    writer = csv.writer(f, quoting=csv.QUOTE_MINIMAL)
    writer.writerow(header)
    for r in rows:
        assert len(r) == len(header), f"Row {r[0]} has {len(r)} cols (expected {len(header)})"
        writer.writerow(r)

print("done, rows:", len(rows))
